[tool.poetry]
name = "prml"
version = "0.1.0"
description = ""
authors = ["zeppfreak <zeppfreak@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
black = "^21.9b0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
